name: sra-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake>=7.32
  - mamba
  - pandas>=2.0
  - numpy
  - matplotlib
  - fastp
  - fastqc
  - multiqc
  - salmon
  - sra-tools
  - pysradb
  - pip
  - pytest
